# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "A smarter way to manage git worktrees"
  homepage "https://github.com/yasomaru/git-wt"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.0.1/git-wt_1.0.1_darwin_amd64.tar.gz"
      sha256 "d24dfd8d2b998bfba911db3ce28075f4dd1c5f797da4e7f0f72d40e1a10c1e88"

      def install
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.0.1/git-wt_1.0.1_darwin_arm64.tar.gz"
      sha256 "fa64505f9410678b13205b25f222b69f553fcbc9dd9509f8ee5e9e19031b565a"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.0.1/git-wt_1.0.1_linux_amd64.tar.gz"
      sha256 "df011b182e148c2cf041a95399447f49c8c900b527326f31cd367597aefba717"
      def install
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.0.1/git-wt_1.0.1_linux_arm64.tar.gz"
      sha256 "6092976de2108f5bf5aca62d2db2ee4dde47d17e0d8f93cafedaeb2312c35a5d"
      def install
        bin.install "git-wt"
      end
    end
  end

  test do
    system "#{bin}/git-wt", "version"
  end
end
