# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "A smarter way to manage git worktrees"
  homepage "https://github.com/yasomaru/git-wt"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.1.0/git-wt_1.1.0_darwin_amd64.tar.gz"
      sha256 "5f1b2041627e060bac08acaaf84afd48de98572c871790808190f02fec45061c"

      def install
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.1.0/git-wt_1.1.0_darwin_arm64.tar.gz"
      sha256 "c26fc45154b4058a063bc649231ff4827da3fbfc0abc69fc71198741b69d2fb2"

      def install
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.1.0/git-wt_1.1.0_linux_amd64.tar.gz"
      sha256 "ea1bcf6305411efc757c0ab7a3836d0c3c6dfd6ec5767e67a8b1c597688bb638"
      def install
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yasomaru/git-wt/releases/download/v1.1.0/git-wt_1.1.0_linux_arm64.tar.gz"
      sha256 "3778501cd60022305eb943bf16ee98b7282b064ecd1845809d7df8e7c2955adb"
      def install
        bin.install "git-wt"
      end
    end
  end

  test do
    system "#{bin}/git-wt", "version"
  end
end
